<?php
/**
 * @file
 * training_event.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function training_event_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function training_event_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function training_event_node_info() {
  $items = array(
    'event_calendar' => array(
      'name' => t('Training Event'),
      'base' => 'node_content',
      'description' => t('A content type to create events for calendar.'),
      'has_title' => '1',
      'title_label' => t('Event Title'),
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implements hook_default_registration_type().
 */
function training_event_default_registration_type() {
  $items = array();
  $items['event_registration'] = entity_import('registration_type', '{
    "name" : "event_registration",
    "label" : "Event Registration",
    "locked" : "0",
    "weight" : "0",
    "data" : null,
    "rdf_mapping" : []
  }');
  return $items;
}
